---
- name: Provision a RHEL VM in VMware
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include VM provisioning role
      ansible.builtin.include_role:
        name: vm_provision
      vars: 
        # fresh_prov: testvm2 # Name of the VM (Deployment from scratch)
        # fresh_os: rhel8_64Guest # OS for the VM (Deployment from scratch)

        fresh_prov_list:
          - { fresh_prov: testvm1, fresh_os: rhel8_64Guest }
          - { fresh_prov: testvm2, fresh_os: windows9_64Guest }

        #template_prov: testvm3 # Name of the VM (Deployment from template)
        #template_name: rhel86-tpl # Name of template (Deployment from template)

        template_prov_list: #Using a hash list
          - { template_prov: testvm3, template_name: testvm1_rhel9, iso_name: rhel-9.2-x86_64-dvd.iso}
          - { template_prov: testvm4, template_name: testvm2_rhel8, iso_name: rhel-8.9-x86_64-dvd.iso}
        
        del_vm_list: 
          - testvm1
          - testvm2
          - testvm3
          - testvm4

    - name: Debug message from AAP
      ansible.builtin.debug:
        msg: "VM ware provisioning main playbook file"