- name: Initiate packer
  ansible.builtin.shell: packer init files/win_server/

- name: Build packer image in vCenter
  ansible.builtin.shell: packer build -var-file="files/win_server/overall.pkrvars.hcl" files/win_server