# Installation packer
# - name: Installing dnf-utils for packer (RHEL)
#   ansible.builtin.yum:
#     name: dnf-utils
#     state: present

- name: Add in hashicorp repository (RHEL)
  ansible.builtin.yum_repository:
    name: hashicorp
    baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: Enabling hashicorp repository (RHEL)
  community.general.dnf_config_manager:
    name: hashicorp
    state: enabled

- name: Installing packer from the new repo (RHEL)
  ansible.builtin.yum:
    name: packer
    state: present
