# Installation packer
- name: Installing dnf-utils for packer (RHEL)
  ansible.builtin.command: yum install -y python3-dnf

- name: Installing dnf-utils for packer (RHEL)
  ansible.builtin.dnf:
    name: dnf-utils
    state: present
  delegate_to: localhost

- name: Add in hashicorp repository (RHEL)
  ansible.builtin.yum_repository:
    name: hashicorp
    baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    description: hashicorp respository
    enabled: true
  delegate_to: localhost

- name: Installing packer from the new repo (RHEL)
  ansible.builtin.dnf:
    name: packer
    state: present
  delegate_to: localhost
