---
# vars file for vm_provision/ vm info
vcenter_hostname: vcsnsx-vc.infra.demo.redhat.com
vcenter_datacenter: SDDC-Datacenter
vcenter_validate_certs: false
vm_folder: Workloads/sandbox-qzqxj
vm_name: "{{ fresh_prov }}"

# List of Hypervisors in the redhat demo (Open Env)
esxi_host1: esxi-01000.infra.demo.redhat.com
esxi_host2: esxi-01001.infra.demo.redhat.com
esxi_host3: esxi-01002.infra.demo.redhat.com

# List of datastores in the redhat demo (Open Env)
datastore1: workload_share_dwPsq
datastore2: workload_share_FZZZD
datastore3: workload_share_Q6pSF
datastore4: workload_share_SYmuF
datastore5: workload_share_yBaQN

# Cluster name (Open Env)
cluster_name: Cluster-1