---
# vars file for vm_provision/ vm info
vcenter_hostname: vmexample.infra.demo.com
vcenter_datacenter: unknown_datacenter
vcenter_validate_certs: false
vm_folder: Workloads/sandbox-abc

# List of Hypervisors in the redhat demo (Open Env)
esxi_host1: esxi01.infra.com
esxi_host2: esxi02.infra.com
esxi_host3: esxi03.infra.com

# List of datastores in the redhat demo (Open Env)
datastore1: workload_share_1
datastore2: workload_share_2
datastore3: workload_share_3
datastore4: workload_share_4
datastore5: workload_share_5

# Cluster name (Open Env)
cluster_name: Cluster-1

# Network variables (dictionary)
network_vars:
    name: sandbox-abc #segment-sandbox-qzqxj
    mac: 00:ab:11:cd:12:15

clone_list: "{{ fresh_prov_list | zip(template_prov_list) }}"