---
- name: Get a particular vm info 
  ansible.builtin.include_tasks:
    file: vm_info.yml

- name: Provision a new vm from scratch
  ansible.builtin.include_tasks:
    file: fresh_provision.yml

- name: Provision VM based on X number of templates
  ansible.builtin.include_tasks:
    file: template_provision.yml
  loop: "{{ template_name }}"

#- name: Provision VM from OVA