---
- name: Get a particular vm info 
  ansible.builtin.include_tasks:
    file: vm_info.yml

- name: Remove VM from the vCenter inventory
  ansible.builtin.include_tasks:
    file: remove_vm.yml
  vars:
    vm_del_name: "{{ item }}"
  loop: "{{ del_vm_list }}"

- name: Provision a new vm from scratch
  ansible.builtin.include_tasks:
    file: fresh_provision.yml

- name: Provision VM based on X number of templates
  ansible.builtin.include_tasks:
    file: template_provision.yml
  vars:
    template_prov: "{{ item.template_prov }}"
    template_name: "{{ item.template_name }}"
  loop: "{{ template_prov_list }}"

- name: Provision VM from OVA
  ansible.builtin.include_tasks:
    file: ovfa_provision.yml