- name: Provision VM based from OVA
  community.vmware.vmware_deploy_ovf:
    hostname: "{{ vcenter_hostname }}"
    datacenter: "{{ vcenter_datacenter }}"
    folder: "{{ vm_folder }}"
    cluster: "{{ cluster_name }}"
    datastore: "{{ datastore1 }}"
    name: ovaftestvm
    ovf: rhel86-tpl #roadshow-tpl-database
  register: ovaftestvm
  delegate_to: localhost

- name: Print the VM info deployed from OVA
  ansible.builtin.debug:
    var: ovaftestvm