- name: Remove a virtual machine from inventory
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    datacenter: "{{ vcenter_datacenter }}"
    folder: "{{ vm_folder }}"
    name: "{{ vm_del_name }}"
    cluster: "{{ cluster_name }}"
    delete_from_inventory: true
    state: absent
    force: true
  delegate_to: localhost