- name: Provision VM based on a template
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    datacenter: "{{ vcenter_datacenter }}"
    folder: "{{ vm_folder }}"
    name: "{{ template_prov }}"
    state: poweredon
    #esxi_hostname: #Set either esxi or cluster
    cluster: "{{ cluster_name }}"
    template: "{{ template_name }}"  #Template or existing VM used to create new virtual machine
    networks:
    - name: segment-sandbox-qzqxj #Name of the portgroup or distributed virtual portgroup for this interface.
      mac: 00:50:56:8e:36:d5
  register: deploy_vm

- name: Print the VM info deployed from template
  ansible.builtin.debug:
    var: deploy_vm